# docker build --network host -t zao111222333/rust-online:yew -f Dockerfile-rust-yew .
# docker push zao111222333/rust-online:yew
# docker run -it \
#   -p 8000:80   \
#   -p 8080:8080 \
#   zao111222333/rust-online:yew
FROM zao111222333/rust-online:basic
RUN apt-get update -y && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
    pkg-config\
    libssl-dev\
    openssl
RUN rustup target add wasm32-unknown-unknown\
 && cargo install trunk\
 && cargo install wasm-bindgen-cli\
 && cargo install wasm-pack\
 && mv /root/.cargo/bin/* /usr/bin/
RUN rm -rf /tmp/* \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

EXPOSE 8080