# docker build --network host -t zao111222333/spinalhdl -f Dockerfile-spinalhdl .

FROM debian:11-slim
#
# jdk
# https://www.oracle.com/java/technologies/downloads/#license-lightbox
ENV JAVA_VERSION 311
ENV JAVA_DIR     /usr/local/oracle-java-8
ENV JAVA_HOME    ${JAVA_DIR}/jdk1.8.0_${JAVA_VERSION}
COPY src/jdk/jdk-8u${JAVA_VERSION}-linux-x64.tar.gz /tmp/jdk-8u${JAVA_VERSION}-linux-x64.tar.gz
RUN cd /tmp \
 && mkdir ${JAVA_DIR} \
 && tar xzf jdk-8u${JAVA_VERSION}-linux-x64.tar.gz -C ${JAVA_DIR} \
 && update-alternatives --install /usr/bin/java   java     ${JAVA_HOME}/bin/java 1500 \
 && update-alternatives --install /usr/bin/javac  javac    ${JAVA_HOME}/bin/javac 1500 \
 && update-alternatives --install /usr/bin/javaws javaws   ${JAVA_HOME}/bin/javaws 1500

#
# scala
# "https://downloads.typesafe.com/scala/2.11.12/scala-2.11.12.tgz"
ENV SCALA_VERSION 2.11.12
ENV SCALA_HOME    /usr/local/scala
ENV PATH ${PATH}:${SCALA_HOME}/bin

COPY src/scala/scala-${SCALA_VERSION}.tgz /tmp/scala-${SCALA_VERSION}.tgz
RUN cd /tmp \
 && tar xzf scala-${SCALA_VERSION}.tgz \
 && mkdir ${SCALA_HOME} \
 && rm /tmp/scala-${SCALA_VERSION}/bin/*.bat \
 && mv /tmp/scala-${SCALA_VERSION}/bin /tmp/scala-${SCALA_VERSION}/lib ${SCALA_HOME}\
 && ln -s ${SCALA_HOME}/bin/* /usr/bin/

#
# sbt
#
ENV SBT_VERSION  1.4.7
ENV SBT_HOME     /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin
COPY src/sbt/sbt-${SBT_VERSION}.tgz /tmp/sbt-${SBT_VERSION}.tgz
RUN cd /tmp \
 && mkdir ${SBT_HOME} \
 && tar -zxvf sbt-${SBT_VERSION}.tgz \
 && mv sbt/* $SBT_HOME \
 && ln -s ${SBT_HOME}/bin/* /usr/bin/

ARG COURSIER_CACHE=/usr/share/sbt/coursier
RUN echo "export COURSIER_CACHE=/usr/share/sbt/coursier" >> /etc/profile \
 && echo "export LC_ALL=C" >> /etc/profile
COPY src/sbt/sbt_config /tmp/sbt_config
RUN mkdir /usr/share/sbt/ \
 && cp -r /tmp/sbt_config/* /usr/share/sbt/ \
 && sed -i "s/-sbt-create*/#-sbt-create/" /usr/local/sbt/conf/sbtopts \
 && sed -i "s/#-sbt-dir  \/etc\/sbt/-sbt-dir \/usr\/share\/sbt/" /usr/local/sbt/conf/sbtopts \
 && sed -i "s/-sbt-boot*/-sbt-boot \/usr\/share\/sbt\/boot/" /usr/local/sbt/conf/sbtopts \
 && sed -i "s/#-ivy ~\/.ivy2/-ivy \/usr\/share\/sbt\/ivy2/" /usr/local/sbt/conf/sbtopts 


# SpinalHDL
# spinalVersion = "1.5.0"
# scalaVersion := "2.11.12"
COPY src/sources.list-bullseye /etc/apt/sources.list
RUN cat /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* \
 && apt-get update -y && apt-get upgrade -y\
 && apt-get install -y --no-install-recommends \
    perl \
    gcc \
    verilator \
    make \
    g++ \
    apt-utils
COPY src/SpinalTemplateSbt /SpinalTemplateSbt
RUN chmod -R a+r /SpinalTemplateSbt \
 && cd /SpinalTemplateSbt \
 && sbt "runMain mylib.MyTopLevelSim"\
 && chmod -R 777 /usr/share/sbt

RUN rm -rf /tmp/* \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean