# docker build --network host -t zao111222333/gtk4 -f gtk4.dockerfile .
# docker run --rm -it -p 5000:5000 zao111222333/gtk4
# docker run --rm -it zao111222333/gtk3
# =============== BUILD =================
FROM debian:11-slim as build
COPY src/sources.list-bullseye /etc/apt/sources.list
RUN cat /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* \
 && apt-get update -y && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    build-essential \
    autoconf \
    autotools-dev \
    pkg-config \
    automake \
    tcl-dev \
    tk-dev \
    gperf \
    libbz2-dev\
    liblzma-dev\
    libgtk-3-dev\
    gtk-doc-tools\
    gnome-common\
    intltool\
    valac\
    libglib2.0-dev\
    gobject-introspection\
    libgirepository1.0-dev\
    libclutter-gtk-1.0-dev\
    libgnome-desktop-3-dev\
    libcanberra-dev\
    libgdata-dev\
    libdbus-glib-1-dev\
    libgstreamer1.0-dev\
    libupower-glib-dev\
    fonts-droid-fallback\
    meson\
    libatk1.0-dev\
    cmake
WORKDIR /Dependencies
COPY src/gtk/Dependencies /Dependencies
# https://www.linuxfromscratch.org/blfs/view/svn/x/atk.html
RUN tar -xf atk-2.36.0.tar.xz\
 && cd atk-2.36.0\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/general/glib2.html
RUN tar -xf glib-2.70.2.tar.xz\
 && cd glib-2.70.2\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release -Dman=true ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/x/at-spi2-core.html
RUN tar -xf at-spi2-core-2.40.3.tar.xz\
 && cd at-spi2-core-2.40.3\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/x/at-spi2-atk.html
RUN tar -xf at-spi2-atk-2.38.0.tar.xz\
 && cd at-spi2-atk-2.38.0\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/x/gdk-pixbuf.html
RUN tar -xf gdk-pixbuf-2.42.6.tar.xz\
 && cd gdk-pixbuf-2.42.6\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release --wrap-mode=nofallback ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/x/libepoxy.html
RUN tar -xf libepoxy-1.5.9.tar.xz\
 && cd libepoxy-1.5.9\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release ..\
 && ninja\
 && ninja install
# https://www.linuxfromscratch.org/blfs/view/svn/x/pango.html
RUN tar -xf pango-1.50.2.tar.xz\
 && cd pango-1.50.2\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release --wrap-mode=nofallback ..\
 && ninja\
 && ninja install

RUN tar -xzf tiff-4.1.0.tar.gz\
 && cd tiff-4.1.0\
 && ./configure\
 && make\
 && make install

RUN tar -xzf jpegsrc.v9d.tar.gz\
 && cd jpeg-9d\
 && ./configure\
 && make\
 && make install

# git clone git://github.com/ebassi/graphene
RUN cd graphene\
 && mkdir build && cd build\
 && meson --prefix=/usr --buildtype=release ..\
 && ninja\
 && ninja install

RUN apt-get install -y --no-install-recommends \
    sassc\
    libgstreamer-plugins-bad1.0-dev
RUN tar -xzf meson-0.60.2.tar.gz

WORKDIR /
COPY src/gtk/gtk4/gtk-main.tar.gz /gtk-main.tar.gz
RUN tar -xzf /gtk-main.tar.gz
COPY src/gtk/gtk4/meson_options.txt /gtk-main/meson_options.txt
RUN cd /gtk-main\
 && mkdir build && cd build\
 && /Dependencies/meson-0.60.2/meson.py\
        --prefix=/opt/gtk/ ..\
 && ninja\
 && ninja install


# =============== RUN =================
FROM debian:11-slim
COPY src/sources.list-bullseye-tuna /etc/apt/sources.list
RUN cat /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* \
 && apt-get update -y && apt-get upgrade -y\
 && apt-get install -y --no-install-recommends \
    libglib2.0-0
    # tk
COPY src/gtk/gtk4/libgtk-4-common_4.4.1+ds1-3_all.deb /tmp/libgtk-4-common_4.4.1+ds1-3_all.deb
RUN apt-get install -y --no-install-recommends /tmp/libgtk-4-common_4.4.1+ds1-3_all.deb
COPY src/gtk/gtk4/libgtk-4-1_4.4.1+ds1-3_amd64.deb /tmp/libgtk-4-1_4.4.1+ds1-3_amd64.deb
RUN apt-get install -y --no-install-recommends /tmp/libgtk-4-1_4.4.1+ds1-3_amd64.deb
COPY --from=build /opt/gtk/     /opt/gtk/
# COPY --from=build /etc/gtk/     /etc/gtk/
# RUN rm -rf /usr/bin/gtk-update-icon-cache\
#  && ln -s /opt/gtkwave/bin/* /usr/bin/\
#  && rm -rf /usr/bin/gtkwave.origin
ENV GDK_BACKEND broadway
EXPOSE 5000

# RUN rm -rf /tmp/* \
#  && rm -rf /var/lib/apt/lists/* \
#  && apt-get clean

COPY entrypoint/docker-entrypoint-gtk4.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"$